### ISSUE TITLE
Gridfinity Generator crashing all the time

### ISSUE THREAD

**Issue by ishidaed** [Le0Michine/FusionGridfinityGenerator#42]
Hey guys, I'm having this error below all the time. Can anyone give me some light? What could it be? How can I solve it? Unfortunately, I'm a designer, not a developer. 

Thanks a lot for your support

"Error: An unknonwn error occurred, please validate your inputs and try again:
Traceback (most recent call last):
  File "/Users/ishida/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/GridfinityGenerator.bundle/Contents/commands/commandCreateBaseplate/entry.py", line 313, in generateBaseplate
    baseplateBody = createGridfinityBaseplate(baseplateGeneratorInput, gridfinityBaseplateComponent)
  File "/Users/ishida/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/GridfinityGenerator.bundle/Contents/lib/gridfinityUtils/baseplateGenerator.py", line 16, in createGridfinityBaseplate
    baseBody = baseGenerator.createBaseWithClearance(cutoutInput, targetComponent)
  File "/Users/ishida/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/GridfinityGenerator.bundle/Contents/lib/gridfinityUtils/baseGenerator.py", line 227, in createBaseWithClearance
    extendFeature = features.extendFeatures.add(extendClearanceSurfaceFeatureInput)
  File "/Users/ishida/Library/Application Support/Autodesk/webdeploy/production/41fc0227d2c69e974bd561da6cdf952ff4bb1cc8/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/fusion.py", line 20182, in add
    return _fusion.ExtendFeatures_add(self, input)
RuntimeError: 5 : Some input argument is invalid."

**Comment by adoolaard** [comment]
I have the same problem occurring. When I attempt to load the "Gridfinity bin" or the "Gridfinity baseplate." I encounter the same error. Before the error appears, I can briefly see the bin or baseplate for about 0.5 seconds, but then it disappears, and the error message pops up.

**Comment by ishidaed** [comment]
> I have the same problem occurring. When I attempt to load the "Gridfinity bin" or the "Gridfinity baseplate." I encounter the same error. Before the error appears, I can briefly see the bin or baseplate for about 0.5 seconds, but then it disappears, and the error message pops up.

exactly the same situation here... 

I'm using it on a Macbook Pro 2015 with the following config

<img width="257" alt="Screen Shot 2023-08-02 at 7 43 44 PM" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/22860516/5c6f232b-f9a9-43bd-9ecc-d59d26bd8cd1">


exactly the same situation here... 

I'm using it on a Macbook Pro 2015 with

**Comment by deadboy25** [comment]
After looking for a solution to this same issue, I discovered it was actually resolved in issue #40 but the creator is waiting on Fusion360 to approve the latest version for their app store.

If you delete the version you have installed now, download the latest version from main, and install it from within Fusion360's plugin manager, it will work as expected.

**Comment by ishidaed** [comment]
> After looking for a solution to this same issue, I discovered it was actually resolved in issue #40 but the creator is waiting on Fusion360 to approve the latest version for their app store.
> 
> If you delete the version you have installed now, download the latest version from main, and install it from within Fusion360's plugin manager, it will work as expected.

I did just that, using version 1.2.0.0 and still not working.. =(

**Comment by Le0Michine** [comment]
Hi, sorry for the delayed response, I’m currently dealing with some urgent personal matters.

Here is the most recent pre release version https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.4.0

it should be v1.2.4.0, the one you mentioned v1.2.0.0 is the one where the bug was discovered.

as for the update in the App Store, I believe it should get published early next week

**Comment by Le0Michine** [comment]
So the release got approved sooner than expected https://apps.autodesk.com/FUSION/en/Detail/Index?id=7197558650811789&appLang=en&os=Mac

let me know if you are still having problems with it

**Comment by adoolaard** [comment]
Thanks a lot, @Le0Michine ! This update works perfectly. Your work is much appreciated, and I wish you all the best!

**Comment by Le0Michine** [comment]
closing this issue as the fix was published both on [github](https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.4.0) and in [autodesk app store](https://apps.autodesk.com/FUSION/en/Detail/Index?id=7197558650811789&appLang=en&os=Mac)

**Comment by ishidaed** [comment]
> Thanks a lot, @Le0Michine ! This update works perfectly. Your work is much appreciated, and I wish you all the best!

I second this... Best addin ever for Fusion360...
